# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

r_github_packages:
  - hadley/devtools

after_success:
  - Rscript -e 'covr::codecov()'

